### ISSUE TITLE
Sign your code?

### ISSUE THREAD

**Issue by DiagonalArg** [ryran/pyrite#18] opened 2013-11-03 14:57 UTC
You should sign your code, man.  Or at least give us some hashes.

(Thanks for your work!)

**Comment by ryran** [comment] 2015-06-02 22:08
I can't believe a whole year went by ... more. Closing as dupe of #7. I really do plan to look into this next month. Will comment there if I need help.

**Closed by ryran** 2015-06-02 22:08 UTC

**Comment by ryran** [comment] 2015-06-23 19:06
Finally done.

https://github.com/ryran/pyrite/releases/tag/v1.0.2

I'll be using signed tags from now on, as well as signing all commits.

**Comment by DiagonalArg** [comment] 2015-07-03 08:19
Dude!  Thank you.  Great little project, by the way ...
